# For root Vagrantfile to keep paths consistent; use in place of '.' in paths
here = File.dirname(__FILE__)

Vagrant.configure("2") do |config|
  box = "cicd"

  num_web     = 1
  num_workers = 1

  has_router = false

  username = "packer"
  password = "packer"

  config.ssh.username = username
  config.ssh.password = password

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 1
    vb.memory = 1024
    # vb.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
    # much faster startups of subsequent identical base VMs, but leaves the base VM in VBox's storage after destroy op
    # vb.linked_clone = true
  end

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  if has_router then
    config.vm.define "cicd-router" do |router|
      router.vm.box = box
      router.vm.network "private_network", ip: "10.0.1.#{rand(20..254)}" # type: "dhcp", name: "vboxnet0"
      router.vm.network "forwarded_port", guest: 80, host: 8080
      router.vm.synced_folder "#{here}", "/vagrant", disabled: true

      router.vm.provision "file", source: "./vars", destination: "/tmp/vars"
      router.vm.provision "file", source: "./router-config", destination: "/tmp/router-config"
      router.vm.provision "shell",
        inline: <<-SCRIPT
          sudo su -
          hostnamectl set-hostname "concourse-router"
          useradd nginx
          apt-get update && apt-get install -y nginx
          cp /tmp/router-config/nginx-vagrant.conf /etc/nginx/nginx.conf
          # NGINX gets mad because you took out the PIDfile, so be careful here
          sleep 1
          systemctl restart nginx
          sleep 3
          ! systemctl is-failed nginx || exit 1
        SCRIPT
    end
  end

  # Numbered according to their last IP int
  (1..num_web).each do |i|
    config.vm.define "cicd-web-#{i}" do |web|
      web.vm.box = box
      web.vm.network "private_network", ip: "10.0.1.#{rand(20..254)}" # type: "dhcp", name: "vboxnet0"
      web.vm.network "forwarded_port", guest: 8080, host: (8080 + i)
      web.vm.synced_folder "#{here}", "/vagrant", disabled: true
      web.vm.provision "shell",
        inline: <<-SCRIPT
          export app_name='cicd-web'
          export configmgmt_address='configmgmt.service.consul'
          bash /usr/local/imgbuilder/scripts/run/main.sh
        SCRIPT
    end
  end

  # Numbered according to their last IP int
  (1..num_workers).each do |i|
    config.vm.define "cicd-worker-#{i}" do |worker|
      worker.vm.box = box
      worker.vm.network "private_network", ip: "10.0.1.#{rand(20..254)}" # type: "dhcp", name: "vboxnet0"
      worker.vm.synced_folder "#{here}", "/vagrant", disabled: true
      worker.vm.provision "shell",
        inline: <<-SCRIPT
          export app_name='cicd-worker'
          export configmgmt_address='configmgmt.service.consul'
          bash /usr/local/imgbuilder/scripts/run/main.sh
        SCRIPT
    end
  end
end
