runtime: &runtime
  platform: linux
  inputs:
  - name: ((repo.name))-src
    path: ((repo.name))
  image_resource:
    type: registry-image
    source: 
      repository: ociregistry.service.consul/library/debian
      tag: latest

task-main: &task-main
  <<: *runtime

resources:
- name: ((repo.name))-src
  source:
    branch: ((repo.branch))
    uri: ((repo.uri))
  type: git

jobs:
- name: build
  plan:
  - get: ((repo.name))-src
    trigger: true
  - task: build
    config:
      <<: *task-main
      run:
        path: bash
        args:
          - '-c'
          - |
            bash ((repo.name))/scripts/sysinit.sh
            make -C ((repo.name)) build
- name: test
  plan:
  - get: ((repo.name))-src
    trigger: true
    passed: [build]
  - task: test
    config:
      <<: *task-main
      run:
        path: bash
        args:
          - '-c'
          - |
            bash ((repo.name))/scripts/sysinit.sh
            make -C ((repo.name)) test
- name: push
  plan:
  - get: ((repo.name))-src
    trigger: true
    passed: [test]
  - task: push
    config:
      <<: *task-main
      run:
        path: bash
        args:
          - '-c'
          - |
            bash ((repo.name))/scripts/sysinit.sh
            make -C ((repo.name)) push

  # - task: try-super-linter
  #   config:
  #     platform: linux
  #     image_resource:
  #       type: registry-image
  #       source:
  #         repository: ghcr.io/github/super-linter
  #         tag: slim-v4
  #     params:
  #       RUN_LOCAL: true
  #       USE_FIND_ALGORITHM: true
  #       IGNORE_GITIGNORED_FILES: true
  #       FILTER_REGEX_EXCLUDE: 'testdata.*'
  #       FILTER_REGEX_EXCLUDE: '.*\.vmdk|.*\.ovf|.*\.box|.*\.iso'
  #       VALIDATE_GO: false
  #       VALIDATE_NATURAL_LANGUAGE: false
  #     run:
  #       path: /action/lib/linter.sh
  # - task: try-rhad
  #   config:
  #     platform: linux
  #     image_resource:
  #       type: registry-image
  #       source:
  #         repository: ghrc.io/opensourcecorp/rhad
  #         tag: latest
  #     run:
  #       path: rhad
  #       args: ["lint"]
