pipeline {
  agent any
  stages {
    stage('Echo') {
      steps {
        println 'Testing Jenkinsfile pickup'
        sh 'ls -la'
      }
    }
    stage('ls in container') {
      agent { docker { image 'alpine:latest' } }
      steps {
        sh 'ls -la'
      }
    }
  }
}
