pipeline {
  agent any
  stages {
    stage('Echo') {
      steps {
        println 'Testing Jenkinsfile pickup'
      }
    }
    stage('ls in container') {
      steps {
        docker.image('alpine:latest').inside {
          sh 'ls -la'
        }
      }
    }
  }
}
