pipeline {
  agent any
  stages {
    stage('Echo') {
      steps {
        println 'Testing Jenkinsfile pickup'
        sh 'ls -la'
      }
    }
    stage('ls in public image container') {
      agent { docker { image 'alpine:latest', reuseNode true } }
      steps {
        sh 'ls -la'
      }
    }
    stage('ls in private image container') {
      agent { docker { image 'ociregistry.service.consul/mirrors/alpine:latest', reuseNode true } }
      steps {
        sh 'ls -la'
      }
    }
  }
}
