# For root Vagrantfile to keep paths consistent; use in place of '.' in paths
here = File.dirname(__FILE__)

Vagrant.configure("2") do |config|
  box = "baseimg"

  num_replicas = 0

  username = "packer"
  password = "packer"

  config.ssh.username = username
  config.ssh.password = password

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 1
    vb.memory = 1024
    # vb.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
    # much faster startups of subsequent identical base VMs, but leaves the base VM in VBox's storage after destroy op
    # vb.linked_clone = true
  end

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  config.vm.define "sourcecode" do |cfg|
    cfg.vm.box = box
    cfg.vm.network "private_network", ip: "10.0.1.#{rand(20..254)}" # type: "dhcp", name: "vboxnet0"
    cfg.vm.network "forwarded_port", guest: 8443, host: 8443
    cfg.vm.synced_folder "#{here}", "/vagrant", disabled: true

    # This script is already on the disk, but this lets us update it with local changes without rebuilding the entire image
    cfg.vm.provision "file", source: "#{here}/../baseimg/scripts/run/main.sh", destination: "/tmp/main.sh"
    cfg.vm.provision "shell", inline: "sudo cp /tmp/main.sh /usr/local/baseimg/scripts/run/main.sh"
    cfg.vm.provision "shell",
      inline: <<-SCRIPT
        export app_name='sourcecode'
        export configmgmt_address='10.0.1.10'
        bash /usr/local/baseimg/scripts/run/main.sh
      SCRIPT
  end

end
