# For root Vagrantfile to keep paths consistent; use in place of '.' in paths
here = File.dirname(__FILE__)

Vagrant.configure("2") do |config|
  box = "faro"

  username = "packer"
  password = "packer"

  config.ssh.username = username
  config.ssh.password = password

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 1
    vb.memory = 1024
    # vb.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
    # much faster startups of subsequent identical base VMs, but leaves the base VM in VBox's storage after destroy op
    # vb.linked_clone = true
  end

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  config.vm.define "faro" do |faro|
    faro.vm.box = box
    faro.vm.network "private_network", ip: "10.0.1.11" # Needs to be static
    ports = [
      {'port' => 8300, 'protocol' => 'tcp'},
      {'port' => 8301, 'protocol' => 'tcp'},
      {'port' => 8301, 'protocol' => 'udp'},
      {'port' => 8302, 'protocol' => 'tcp'},
      {'port' => 8302, 'protocol' => 'udp'},
      {'port' => 8500, 'protocol' => 'tcp'},
      {'port' => 8501, 'protocol' => 'tcp'},
      {'port' => 8502, 'protocol' => 'tcp'},
      # {'port' => 8600, 'protocol' => 'tcp'} # commenting out to test mapping to 53 instead
      # {'port' => 8600, 'protocol' => 'udp'} # commenting out to test mapping to 53 instead
    ]
    ports.each do |net|
      faro.vm.network "forwarded_port", guest: net['port'], host: net['port'], protocol: net['protocol']
    end
    faro.vm.synced_folder "#{here}", "/vagrant", disabled: true
    faro.vm.provision "shell",
      inline: <<-SCRIPT
        export app_name='faro'
        export aether_address='10.0.1.10'
        bash /usr/local/ymir/scripts/run/main.sh
      SCRIPT
  end

end
